-- ScholarSync Seed Data
-- =====================
-- This file is for REFERENCE only.
-- The actual seeding is performed by the POST /api/seed endpoint,
-- which creates auth users, then populates all tables dynamically
-- with realistic production-quality data.
--
-- To seed: POST to /api/seed (requires SUPABASE_SERVICE_ROLE_KEY in env)
--
-- What gets created:
--   • 1 academic year (2025-26, Indian school calendar April-March)
--   • 6 subjects (Math, English, Science, SST, Hindi, CS)
--   • 6 classes (Class 5-A through Class 10-A)
--   • 36 class-subject mappings
--   • 60 students (10/class, realistic Indian names, staggered enrollment)
--   • 1 admin, 4 teachers, 30 parents (auth users with profiles)
--   • 60 parent-student relationships
--   • ~885 attendance records (15 school days, Mon-Sat, ~92% rate)
--   • 18 assignments (3/class, varied subjects and types)
--   • ~160 grades (bell-curve distribution with teacher remarks)
--   • ~120 fee payments (4 fee types, mix of paid/partial/pending/overdue)
--   • 8 announcements (realistic school communications, staggered dates)
--   • ~180 timetable periods (6 periods/day × 5 days × 6 classes)
--   • 18 examinations (3/class: unit tests + mid-terms)
--   • ~160 exam results (bell-curve marks)
--   • 12 admission applications (mixed statuses)
--   • 12 library books (textbooks, fiction, reference)
--   • 20 book issues (issued, returned, overdue)
--   • 8 events (sports day, science fair, PTM, etc.)
--   • 4 transport routes with 30 student assignments
--   • 12 inventory items (furniture, electronics, lab equipment)
--   • 8 payroll records (4 teachers × 2 months)
--   • 7 messages (admin-teacher, teacher-parent communication)
--
-- Demo accounts:
--   admin@scholarsync.demo     / demo123456
--   teacher@scholarsync.demo   / demo123456
--   parent@scholarsync.demo    / demo123456
